### ISSUE TITLE
run the project

### ISSUE THREAD

**Issue by zaszlo** [jakblak/learn-angular2#1]
I have angular-cli and I think this the de facto tool now for project creation/management.
Having difficulties with trying out the angular2 projects from here, is it that the project is deprecated relative to newer npm/angular-cli?

I get these messages when I try to start the project (last one):

```
> tsc && concurrently "tsc -w" "lite-server" 

app/books/book-details/book-details.component.ts(14,14): error TS2420: Class 'BookDetailsComponent' incorrectly implements interface 'OnDestroy'.
  Property 'ngOnDestroy' is missing in type 'BookDetailsComponent'.

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.


0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v7.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular-quickstart@1.0.0~prestart: angular-quickstart@1.0.0
6 silly lifecycle angular-quickstart@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular-quickstart@1.0.0~start: angular-quickstart@1.0.0
8 verbose lifecycle angular-quickstart@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular-quickstart@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/laci/Dev/bookDetails/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle angular-quickstart@1.0.0~start: CWD: /home/laci/Dev/bookDetails
11 silly lifecycle angular-quickstart@1.0.0~start: Args: [ '-c', 'tsc && concurrently "tsc -w" "lite-server" ' ]
12 silly lifecycle angular-quickstart@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle angular-quickstart@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-quickstart@1.0.0
16 verbose cwd /home/laci/Dev/bookDetails
17 error Linux 4.4.0-62-generic
18 error argv "/usr/local/bin/node" "/usr/bin/npm" "start"
19 error node v7.4.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
22 error Exit status 2
23 error Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "tsc -w" "lite-server"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]


```

**Comment by jakblak** [comment]
This project does not use the angular cli.  The difference is here we're using SystemJS module loader.  Angular cli uses webpack as the module loader.
