### ISSUE TITLE
npm start throws error

### ISSUE THREAD

**Issue by coder-strange** [jakblak/learn-angular2#2]
![npm error](https://cloud.githubusercontent.com/assets/19469610/25063168/e219aae0-21fa-11e7-9517-b63285ef65e5.PNG)
[Repo](https://github.com/jakblak/learn-angular2/tree/master/1_starter), This is the repo that I'm using and getting below error.

```
 Error occured when executing command: lite-server
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1050:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:607:11)
     at run (bootstrap_node.js:423:7)
     at startup (bootstrap_node.js:147:9)
     at bootstrap_node.js:538:3
 Error occured when executing command: lite-server
 Error: spawn cmd.exe ENOENT
     at exports._errnoException (util.js:1050:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:367:16)
     at _combinedTickCallback (internal/process/next_tick.js:80:11)
     at process._tickCallback (internal/process/next_tick.js:104:9)
     at Module.runMain (module.js:607:11)
     at run (bootstrap_node.js:423:7)
     at startup (bootstrap_node.js:147:9)
     at bootstrap_node.js:538:3
[1] lite-server exited with code -4058
```
I'm working on windows 8, node 7.9 and npm 4.2

**Comment by jakblak** [comment]
try re-installing your node_modules

OR

try changing the start in package.json from

"start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" "
to:

"start": "concurrently \"npm run tsc:w\" \"npm run lite\" "

OR

Error Solved : By adding C:\Windows\System32 to the environment variables in windows.

OR

find more solutions by googling your main error: error occurred when executing command lite-server

**Comment by coder-strange** [comment]
Changed "start": "tsc && concurrently "npm run tsc:w" "npm run lite" ",
Installed run and lite globally and it works (y), Thank you @jakblak
